name: flutter_hr_app
description: App related to HR planner
publish_to: 'none'
version: 1.0.5+33
environment:
  sdk: ">=2.10.3 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  flutter_nfc_plugin:
    git:
      url: https://github.com/dukhanov/flutter-nfc-plugin.git
      ref: master
  flutter_localizations:
    sdk: flutter
  audioplayers: ^0.20.1
  mailer: any
  http: ^0.13.1
  camera: ^0.5.5
  flutter_audio_recorder2: ^0.0.1
  device_info: ^2.0.2
  encrypt: ^5.0.1
  flutter_email_sender: ^2.2.0
  latlong: ^0.6.1
  latlng: ^0.1.0
  firebase_auth: ^3.3.17
  tuple: ^1.0.2
  flutter_logs: ^2.1.5
  flutter_sensors: ^0.1.6
  flutter_speed_dial: ^4.2.0
  connectivity: ^3.0.6
  html: ^0.15.0
  in_app_update: ^3.0.0
  flutter_spinkit: ^5.0.0
  fluttertoast: ^8.0.8
  geolocator: ^4.0.3
  geocoding: ^2.0.1
  geocoder: ^0.2.1
  positioned_tap_detector_2: ^1.0.0
  location: ^4.3.0
  image_picker: ^0.8.3+3
  ntp: ^2.0.0
  package_info: ^2.0.2
  path_provider: any
  qr_code_scanner: ^0.5.2
  qrcode: ^1.0.4
  sensors: ^2.0.3
  sqflite: ^2.0.0+3
  shared_preferences: ^2.0.7
  launch_review: ^3.0.1
  store_launcher: ^1.0.1
  timer_builder: ^2.0.0
  uuid: ^3.0.4
  transparent_image: ^1.0.0
  async: ^2.1.0
  google_sign_in: any
  dropdown_button2: ^1.2.5
  flutter_image: ^3.0.0
  vector_math: ^2.0.0
  proj4dart: ^1.0.4
  meta: ^1.1.0
  collection: ^1.14.0
  video_player: ^2.1.14
  flutter_gradient_colors: ^2.1.1
  audioplayer: ^0.8.1
  flutter_map: any
  location_platform_interface: ^2.3.0
  cupertino_icons: ^1.0.3
  background_fetch: ^1.0.1
  connectivity_plus: ^2.0.2
  just_audio: any
  path: any
  path_provider_ex: any
  flutter_file_manager: any
  mime: any
  flutter_nfc_reader:
    git:
      url: https://github.com/matteocrippa/flutter-nfc-reader.git
      ref: develop
  google_maps_flutter: ^2.1.5
  flutter_cache_manager: ^3.3.0
dev_dependencies:
  flutter_launcher_icons: ^0.9.2
  flutter_test:
    sdk: flutter
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/Winit/HSM2.png"
flutter:
  uses-material-design: true
  assets:
    - hrplanner.png
    - sao@3x.png
    - tiao@3x.png
    - assets/Winit/
    - assets/Audio/
  fonts:
    - family: Montserrat
      fonts:
        - asset: fonts/Montserrat-Regular.ttf